### ISSUE TITLE
Annotation question

### ISSUE THREAD

**Issue by xxy103** [sunyumail93/PipeRNAseq#1]
Hi Dr. Sun,

Thanks for your PipeRNAseq pipeline, it is quite useful for my data analysis.
May I ask how you cleaned the original GTF files?
Or could you please add a little description about the Annotation files such as the "RefSeq.reduced.bed12.geneid.gtf", "RefSeq.reduced.mRNA.cds.bed12.tx.STOP". 

Best,
Xuan

**Comment by sunyumail93** [comment]
Hi Xuan,

I am glad to hear this pipeline is useful to you. I just added more instructions about how to generate the annotation files here:
https://github.com/sunyumail93/PipeRNAseq/blob/master/preprocessing/Preprocessing.md

RefSeq.reduced.bed12.geneid.gtf is critical for building the STAR index, and it will also be used in the featureCounts step. The above preprocessing steps are mainly because the mouse RefSeq GTF file has duplicated transcripts, and I tried to keep only one copy of each. If your GTF file doesn't have duplicated transcripts (i.e., same transcript name, but occurs multiple times on different locations of the genome), you can directly rename your GTF to GENOME.RefSeq.reduced.bed12.geneid.gtf.

RefSeq.reduced.mRNA.cds.bed12.tx.STOP file is actually not used in PipeRNAseq.sh. It contains the stop codon annotation and will be used in the Ribo-seq pipeline I am developing, so you can delete or ignore it. Sorry about the confusion. I just hope different pipelines (PipeRiboseq, PipeSmRNAseq, etc) can share the GENOME folder.

If you are working on a genome that is not included in the pipeline, I am happy to help with generating the annotation. Let me know if you have any questions.

Thanks,
Yu

**Comment by xxy103** [comment]
Hi Dr. Sun,

Many thanks for your detailed explanation of the pipeline.
It is crystal clear.

Best,
Xuan

**Comment by sunyumail93** [comment]
Hi Xuan,

Thanks for the feedback. I am glad to hear that.

Thanks,
Yu
